// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-O4juCMMa-Ugmq8WfT6W0Icsq0McXNxs',
    appId: '1:447857003968:android:d74fbaaf5cf346e0c38c25',
    messagingSenderId: '447857003968',
    projectId: 'quickfit-8970c',
    storageBucket: 'quickfit-8970c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-O4juCMMa-Ugmq8WfT6W0Icsq0McXNxs',
    appId: '1:447857003968:web:d74fbaaf5cf346e0c38c25',
    messagingSenderId: '447857003968',
    projectId: 'quickfit-8970c',
    authDomain: 'quickfit-8970c.firebaseapp.com',
    storageBucket: 'quickfit-8970c.firebasestorage.app',
  );
}