// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIpVyiX2MSDkg8ocN1j60XKqMnXLJ8vl4',
    appId: '1:644942822762:android:639bd83e6e8a5a80eab913',
    messagingSenderId: '644942822762',
    projectId: 'quickfit-app-6ab63',
    storageBucket: 'quickfit-app-6ab63.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCExHVtLv0hs8DGYASCmkjtDTBJKTP99SE',
    appId: '1:644942822762:web:3202732653f611e9eab913',
    messagingSenderId: '644942822762',
    projectId: 'quickfit-app-6ab63',
    authDomain: 'quickfit-app-6ab63.firebaseapp.com',
    storageBucket: 'quickfit-app-6ab63.firebasestorage.app',
  );
}